

# DataSource Config
spring:
  datasource:
    username: root
    password: 02191219hh
    url: jdbc:mysql://127.0.0.1:3306/platform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 7002
  context-path: /platform

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml